package com.anurag.allocator.service.strategy.impl;

import com.anurag.allocator.service.strategy.NumberGenerationStrategy;

/**
 * A decorator of {@link NumberGenerationStrategy} that bounds the numbers generated by {@code this}
 * strategy
 */
public class BoundedNumberGenerationStrategyDecorator implements NumberGenerationStrategy {
    private final NumberGenerationStrategy numberGenerationStrategy;
    private final Long bound;

    public BoundedNumberGenerationStrategyDecorator(NumberGenerationStrategy numberGenerationStrategy, Long bound) {
        this.numberGenerationStrategy = numberGenerationStrategy;
        this.bound = bound;
    }

    @Override
    public Long nextNumber(long id) {
        Long number = numberGenerationStrategy.nextNumber(id);
        return number <= bound ? number : null;
    }

    @Override
    public boolean validate(long num) {
        return numberGenerationStrategy.validate(num) && num <= bound;
    }
}
